start                  : An error occurred while trying to connect to the Java server (127.0.0.1:45145)
Traceback (most recent call last):
  File "/mnt/data/ikruzhilov/miniconda3/envs/embenv/lib/python3.8/site-packages/pyspark/python/lib/py4j-0.10.9-src.zip/py4j/java_gateway.py", line 977, in _get_connection
    connection = self.deque.pop()
IndexError: pop from an empty deque

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/data/ikruzhilov/miniconda3/envs/embenv/lib/python3.8/site-packages/pyspark/python/lib/py4j-0.10.9-src.zip/py4j/java_gateway.py", line 1115, in start
    self.socket.connect((self.address, self.port))
ConnectionRefusedError: [Errno 111] Connection refused
start                  : An error occurred while trying to connect to the Java server (127.0.0.1:45145)
Traceback (most recent call last):
  File "/mnt/data/ikruzhilov/miniconda3/envs/embenv/lib/python3.8/site-packages/pyspark/python/lib/py4j-0.10.9-src.zip/py4j/java_gateway.py", line 977, in _get_connection
    connection = self.deque.pop()
IndexError: pop from an empty deque

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/data/ikruzhilov/miniconda3/envs/embenv/lib/python3.8/site-packages/pyspark/python/lib/py4j-0.10.9-src.zip/py4j/java_gateway.py", line 1115, in start
    self.socket.connect((self.address, self.port))
ConnectionRefusedError: [Errno 111] Connection refused
start                  : An error occurred while trying to connect to the Java server (127.0.0.1:45145)
Traceback (most recent call last):
  File "/mnt/data/ikruzhilov/miniconda3/envs/embenv/lib/python3.8/site-packages/pyspark/python/lib/py4j-0.10.9-src.zip/py4j/java_gateway.py", line 977, in _get_connection
    connection = self.deque.pop()
IndexError: pop from an empty deque

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/data/ikruzhilov/miniconda3/envs/embenv/lib/python3.8/site-packages/pyspark/python/lib/py4j-0.10.9-src.zip/py4j/java_gateway.py", line 1115, in start
    self.socket.connect((self.address, self.port))
ConnectionRefusedError: [Errno 111] Connection refused
start                  : An error occurred while trying to connect to the Java server (127.0.0.1:45145)
Traceback (most recent call last):
  File "/mnt/data/ikruzhilov/miniconda3/envs/embenv/lib/python3.8/site-packages/pyspark/python/lib/py4j-0.10.9-src.zip/py4j/java_gateway.py", line 977, in _get_connection
    connection = self.deque.pop()
IndexError: pop from an empty deque

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/data/ikruzhilov/miniconda3/envs/embenv/lib/python3.8/site-packages/pyspark/python/lib/py4j-0.10.9-src.zip/py4j/java_gateway.py", line 1115, in start
    self.socket.connect((self.address, self.port))
ConnectionRefusedError: [Errno 111] Connection refused
start                  : An error occurred while trying to connect to the Java server (127.0.0.1:45145)
Traceback (most recent call last):
  File "/mnt/data/ikruzhilov/miniconda3/envs/embenv/lib/python3.8/site-packages/pyspark/python/lib/py4j-0.10.9-src.zip/py4j/java_gateway.py", line 977, in _get_connection
    connection = self.deque.pop()
IndexError: pop from an empty deque

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/data/ikruzhilov/miniconda3/envs/embenv/lib/python3.8/site-packages/pyspark/python/lib/py4j-0.10.9-src.zip/py4j/java_gateway.py", line 1115, in start
    self.socket.connect((self.address, self.port))
ConnectionRefusedError: [Errno 111] Connection refused
start                  : An error occurred while trying to connect to the Java server (127.0.0.1:45145)
Traceback (most recent call last):
  File "/mnt/data/ikruzhilov/miniconda3/envs/embenv/lib/python3.8/site-packages/pyspark/python/lib/py4j-0.10.9-src.zip/py4j/java_gateway.py", line 977, in _get_connection
    connection = self.deque.pop()
IndexError: pop from an empty deque

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/data/ikruzhilov/miniconda3/envs/embenv/lib/python3.8/site-packages/pyspark/python/lib/py4j-0.10.9-src.zip/py4j/java_gateway.py", line 1115, in start
    self.socket.connect((self.address, self.port))
ConnectionRefusedError: [Errno 111] Connection refused
start                  : An error occurred while trying to connect to the Java server (127.0.0.1:45145)
Traceback (most recent call last):
  File "/mnt/data/ikruzhilov/miniconda3/envs/embenv/lib/python3.8/site-packages/pyspark/python/lib/py4j-0.10.9-src.zip/py4j/java_gateway.py", line 977, in _get_connection
    connection = self.deque.pop()
IndexError: pop from an empty deque

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/data/ikruzhilov/miniconda3/envs/embenv/lib/python3.8/site-packages/pyspark/python/lib/py4j-0.10.9-src.zip/py4j/java_gateway.py", line 1115, in start
    self.socket.connect((self.address, self.port))
ConnectionRefusedError: [Errno 111] Connection refused
start                  : An error occurred while trying to connect to the Java server (127.0.0.1:45145)
Traceback (most recent call last):
  File "/mnt/data/ikruzhilov/miniconda3/envs/embenv/lib/python3.8/site-packages/pyspark/python/lib/py4j-0.10.9-src.zip/py4j/java_gateway.py", line 977, in _get_connection
    connection = self.deque.pop()
IndexError: pop from an empty deque

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/data/ikruzhilov/miniconda3/envs/embenv/lib/python3.8/site-packages/pyspark/python/lib/py4j-0.10.9-src.zip/py4j/java_gateway.py", line 1115, in start
    self.socket.connect((self.address, self.port))
ConnectionRefusedError: [Errno 111] Connection refused
start                  : An error occurred while trying to connect to the Java server (127.0.0.1:45145)
Traceback (most recent call last):
  File "/mnt/data/ikruzhilov/miniconda3/envs/embenv/lib/python3.8/site-packages/pyspark/python/lib/py4j-0.10.9-src.zip/py4j/java_gateway.py", line 977, in _get_connection
    connection = self.deque.pop()
IndexError: pop from an empty deque

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/data/ikruzhilov/miniconda3/envs/embenv/lib/python3.8/site-packages/pyspark/python/lib/py4j-0.10.9-src.zip/py4j/java_gateway.py", line 1115, in start
    self.socket.connect((self.address, self.port))
ConnectionRefusedError: [Errno 111] Connection refused
start                  : An error occurred while trying to connect to the Java server (127.0.0.1:45145)
Traceback (most recent call last):
  File "/mnt/data/ikruzhilov/miniconda3/envs/embenv/lib/python3.8/site-packages/pyspark/python/lib/py4j-0.10.9-src.zip/py4j/java_gateway.py", line 977, in _get_connection
    connection = self.deque.pop()
IndexError: pop from an empty deque

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/data/ikruzhilov/miniconda3/envs/embenv/lib/python3.8/site-packages/pyspark/python/lib/py4j-0.10.9-src.zip/py4j/java_gateway.py", line 1115, in start
    self.socket.connect((self.address, self.port))
ConnectionRefusedError: [Errno 111] Connection refused
start                  : An error occurred while trying to connect to the Java server (127.0.0.1:45145)
Traceback (most recent call last):
  File "/mnt/data/ikruzhilov/miniconda3/envs/embenv/lib/python3.8/site-packages/pyspark/python/lib/py4j-0.10.9-src.zip/py4j/java_gateway.py", line 977, in _get_connection
    connection = self.deque.pop()
IndexError: pop from an empty deque

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/data/ikruzhilov/miniconda3/envs/embenv/lib/python3.8/site-packages/pyspark/python/lib/py4j-0.10.9-src.zip/py4j/java_gateway.py", line 1115, in start
    self.socket.connect((self.address, self.port))
ConnectionRefusedError: [Errno 111] Connection refused
start                  : An error occurred while trying to connect to the Java server (127.0.0.1:45145)
Traceback (most recent call last):
  File "/mnt/data/ikruzhilov/miniconda3/envs/embenv/lib/python3.8/site-packages/pyspark/python/lib/py4j-0.10.9-src.zip/py4j/java_gateway.py", line 977, in _get_connection
    connection = self.deque.pop()
IndexError: pop from an empty deque

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/data/ikruzhilov/miniconda3/envs/embenv/lib/python3.8/site-packages/pyspark/python/lib/py4j-0.10.9-src.zip/py4j/java_gateway.py", line 1115, in start
    self.socket.connect((self.address, self.port))
ConnectionRefusedError: [Errno 111] Connection refused
start                  : An error occurred while trying to connect to the Java server (127.0.0.1:45145)
Traceback (most recent call last):
  File "/mnt/data/ikruzhilov/miniconda3/envs/embenv/lib/python3.8/site-packages/pyspark/python/lib/py4j-0.10.9-src.zip/py4j/java_gateway.py", line 977, in _get_connection
    connection = self.deque.pop()
IndexError: pop from an empty deque

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/data/ikruzhilov/miniconda3/envs/embenv/lib/python3.8/site-packages/pyspark/python/lib/py4j-0.10.9-src.zip/py4j/java_gateway.py", line 1115, in start
    self.socket.connect((self.address, self.port))
ConnectionRefusedError: [Errno 111] Connection refused
start                  : An error occurred while trying to connect to the Java server (127.0.0.1:45145)
Traceback (most recent call last):
  File "/mnt/data/ikruzhilov/miniconda3/envs/embenv/lib/python3.8/site-packages/pyspark/python/lib/py4j-0.10.9-src.zip/py4j/java_gateway.py", line 977, in _get_connection
    connection = self.deque.pop()
IndexError: pop from an empty deque

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/data/ikruzhilov/miniconda3/envs/embenv/lib/python3.8/site-packages/pyspark/python/lib/py4j-0.10.9-src.zip/py4j/java_gateway.py", line 1115, in start
    self.socket.connect((self.address, self.port))
ConnectionRefusedError: [Errno 111] Connection refused
start                  : An error occurred while trying to connect to the Java server (127.0.0.1:45145)
Traceback (most recent call last):
  File "/mnt/data/ikruzhilov/miniconda3/envs/embenv/lib/python3.8/site-packages/pyspark/python/lib/py4j-0.10.9-src.zip/py4j/java_gateway.py", line 977, in _get_connection
    connection = self.deque.pop()
IndexError: pop from an empty deque

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/data/ikruzhilov/miniconda3/envs/embenv/lib/python3.8/site-packages/pyspark/python/lib/py4j-0.10.9-src.zip/py4j/java_gateway.py", line 1115, in start
    self.socket.connect((self.address, self.port))
ConnectionRefusedError: [Errno 111] Connection refused
start                  : An error occurred while trying to connect to the Java server (127.0.0.1:45145)
Traceback (most recent call last):
  File "/mnt/data/ikruzhilov/miniconda3/envs/embenv/lib/python3.8/site-packages/pyspark/python/lib/py4j-0.10.9-src.zip/py4j/java_gateway.py", line 977, in _get_connection
    connection = self.deque.pop()
IndexError: pop from an empty deque

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/data/ikruzhilov/miniconda3/envs/embenv/lib/python3.8/site-packages/pyspark/python/lib/py4j-0.10.9-src.zip/py4j/java_gateway.py", line 1115, in start
    self.socket.connect((self.address, self.port))
ConnectionRefusedError: [Errno 111] Connection refused
start                  : An error occurred while trying to connect to the Java server (127.0.0.1:45145)
Traceback (most recent call last):
  File "/mnt/data/ikruzhilov/miniconda3/envs/embenv/lib/python3.8/site-packages/pyspark/python/lib/py4j-0.10.9-src.zip/py4j/java_gateway.py", line 977, in _get_connection
    connection = self.deque.pop()
IndexError: pop from an empty deque

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/data/ikruzhilov/miniconda3/envs/embenv/lib/python3.8/site-packages/pyspark/python/lib/py4j-0.10.9-src.zip/py4j/java_gateway.py", line 1115, in start
    self.socket.connect((self.address, self.port))
ConnectionRefusedError: [Errno 111] Connection refused
start                  : An error occurred while trying to connect to the Java server (127.0.0.1:45145)
Traceback (most recent call last):
  File "/mnt/data/ikruzhilov/miniconda3/envs/embenv/lib/python3.8/site-packages/pyspark/python/lib/py4j-0.10.9-src.zip/py4j/java_gateway.py", line 977, in _get_connection
    connection = self.deque.pop()
IndexError: pop from an empty deque

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/data/ikruzhilov/miniconda3/envs/embenv/lib/python3.8/site-packages/pyspark/python/lib/py4j-0.10.9-src.zip/py4j/java_gateway.py", line 1115, in start
    self.socket.connect((self.address, self.port))
ConnectionRefusedError: [Errno 111] Connection refused
start                  : An error occurred while trying to connect to the Java server (127.0.0.1:45145)
Traceback (most recent call last):
  File "/mnt/data/ikruzhilov/miniconda3/envs/embenv/lib/python3.8/site-packages/pyspark/python/lib/py4j-0.10.9-src.zip/py4j/java_gateway.py", line 977, in _get_connection
    connection = self.deque.pop()
IndexError: pop from an empty deque

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/data/ikruzhilov/miniconda3/envs/embenv/lib/python3.8/site-packages/pyspark/python/lib/py4j-0.10.9-src.zip/py4j/java_gateway.py", line 1115, in start
    self.socket.connect((self.address, self.port))
ConnectionRefusedError: [Errno 111] Connection refused
start                  : An error occurred while trying to connect to the Java server (127.0.0.1:45145)
Traceback (most recent call last):
  File "/mnt/data/ikruzhilov/miniconda3/envs/embenv/lib/python3.8/site-packages/pyspark/python/lib/py4j-0.10.9-src.zip/py4j/java_gateway.py", line 977, in _get_connection
    connection = self.deque.pop()
IndexError: pop from an empty deque

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/data/ikruzhilov/miniconda3/envs/embenv/lib/python3.8/site-packages/pyspark/python/lib/py4j-0.10.9-src.zip/py4j/java_gateway.py", line 1115, in start
    self.socket.connect((self.address, self.port))
ConnectionRefusedError: [Errno 111] Connection refused
start                  : An error occurred while trying to connect to the Java server (127.0.0.1:45145)
Traceback (most recent call last):
  File "/mnt/data/ikruzhilov/miniconda3/envs/embenv/lib/python3.8/site-packages/pyspark/python/lib/py4j-0.10.9-src.zip/py4j/java_gateway.py", line 977, in _get_connection
    connection = self.deque.pop()
IndexError: pop from an empty deque

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/data/ikruzhilov/miniconda3/envs/embenv/lib/python3.8/site-packages/pyspark/python/lib/py4j-0.10.9-src.zip/py4j/java_gateway.py", line 1115, in start
    self.socket.connect((self.address, self.port))
ConnectionRefusedError: [Errno 111] Connection refused
start                  : An error occurred while trying to connect to the Java server (127.0.0.1:45145)
Traceback (most recent call last):
  File "/mnt/data/ikruzhilov/miniconda3/envs/embenv/lib/python3.8/site-packages/pyspark/python/lib/py4j-0.10.9-src.zip/py4j/java_gateway.py", line 977, in _get_connection
    connection = self.deque.pop()
IndexError: pop from an empty deque

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/data/ikruzhilov/miniconda3/envs/embenv/lib/python3.8/site-packages/pyspark/python/lib/py4j-0.10.9-src.zip/py4j/java_gateway.py", line 1115, in start
    self.socket.connect((self.address, self.port))
ConnectionRefusedError: [Errno 111] Connection refused
start                  : An error occurred while trying to connect to the Java server (127.0.0.1:45145)
Traceback (most recent call last):
  File "/mnt/data/ikruzhilov/miniconda3/envs/embenv/lib/python3.8/site-packages/pyspark/python/lib/py4j-0.10.9-src.zip/py4j/java_gateway.py", line 977, in _get_connection
    connection = self.deque.pop()
IndexError: pop from an empty deque

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/data/ikruzhilov/miniconda3/envs/embenv/lib/python3.8/site-packages/pyspark/python/lib/py4j-0.10.9-src.zip/py4j/java_gateway.py", line 1115, in start
    self.socket.connect((self.address, self.port))
ConnectionRefusedError: [Errno 111] Connection refused
start                  : An error occurred while trying to connect to the Java server (127.0.0.1:45145)
Traceback (most recent call last):
  File "/mnt/data/ikruzhilov/miniconda3/envs/embenv/lib/python3.8/site-packages/pyspark/python/lib/py4j-0.10.9-src.zip/py4j/java_gateway.py", line 977, in _get_connection
    connection = self.deque.pop()
IndexError: pop from an empty deque

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/data/ikruzhilov/miniconda3/envs/embenv/lib/python3.8/site-packages/pyspark/python/lib/py4j-0.10.9-src.zip/py4j/java_gateway.py", line 1115, in start
    self.socket.connect((self.address, self.port))
ConnectionRefusedError: [Errno 111] Connection refused
start                  : An error occurred while trying to connect to the Java server (127.0.0.1:45145)
Traceback (most recent call last):
  File "/mnt/data/ikruzhilov/miniconda3/envs/embenv/lib/python3.8/site-packages/pyspark/python/lib/py4j-0.10.9-src.zip/py4j/java_gateway.py", line 977, in _get_connection
    connection = self.deque.pop()
IndexError: pop from an empty deque

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/data/ikruzhilov/miniconda3/envs/embenv/lib/python3.8/site-packages/pyspark/python/lib/py4j-0.10.9-src.zip/py4j/java_gateway.py", line 1115, in start
    self.socket.connect((self.address, self.port))
ConnectionRefusedError: [Errno 111] Connection refused
start                  : An error occurred while trying to connect to the Java server (127.0.0.1:45145)
Traceback (most recent call last):
  File "/mnt/data/ikruzhilov/miniconda3/envs/embenv/lib/python3.8/site-packages/pyspark/python/lib/py4j-0.10.9-src.zip/py4j/java_gateway.py", line 977, in _get_connection
    connection = self.deque.pop()
IndexError: pop from an empty deque

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/data/ikruzhilov/miniconda3/envs/embenv/lib/python3.8/site-packages/pyspark/python/lib/py4j-0.10.9-src.zip/py4j/java_gateway.py", line 1115, in start
    self.socket.connect((self.address, self.port))
ConnectionRefusedError: [Errno 111] Connection refused
start                  : An error occurred while trying to connect to the Java server (127.0.0.1:45145)
Traceback (most recent call last):
  File "/mnt/data/ikruzhilov/miniconda3/envs/embenv/lib/python3.8/site-packages/pyspark/python/lib/py4j-0.10.9-src.zip/py4j/java_gateway.py", line 977, in _get_connection
    connection = self.deque.pop()
IndexError: pop from an empty deque

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/data/ikruzhilov/miniconda3/envs/embenv/lib/python3.8/site-packages/pyspark/python/lib/py4j-0.10.9-src.zip/py4j/java_gateway.py", line 1115, in start
    self.socket.connect((self.address, self.port))
ConnectionRefusedError: [Errno 111] Connection refused
start                  : An error occurred while trying to connect to the Java server (127.0.0.1:45145)
Traceback (most recent call last):
  File "/mnt/data/ikruzhilov/miniconda3/envs/embenv/lib/python3.8/site-packages/pyspark/python/lib/py4j-0.10.9-src.zip/py4j/java_gateway.py", line 977, in _get_connection
    connection = self.deque.pop()
IndexError: pop from an empty deque

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/data/ikruzhilov/miniconda3/envs/embenv/lib/python3.8/site-packages/pyspark/python/lib/py4j-0.10.9-src.zip/py4j/java_gateway.py", line 1115, in start
    self.socket.connect((self.address, self.port))
ConnectionRefusedError: [Errno 111] Connection refused
start                  : An error occurred while trying to connect to the Java server (127.0.0.1:45145)
Traceback (most recent call last):
  File "/mnt/data/ikruzhilov/miniconda3/envs/embenv/lib/python3.8/site-packages/pyspark/python/lib/py4j-0.10.9-src.zip/py4j/java_gateway.py", line 977, in _get_connection
    connection = self.deque.pop()
IndexError: pop from an empty deque

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/data/ikruzhilov/miniconda3/envs/embenv/lib/python3.8/site-packages/pyspark/python/lib/py4j-0.10.9-src.zip/py4j/java_gateway.py", line 1115, in start
    self.socket.connect((self.address, self.port))
ConnectionRefusedError: [Errno 111] Connection refused
start                  : An error occurred while trying to connect to the Java server (127.0.0.1:45145)
Traceback (most recent call last):
  File "/mnt/data/ikruzhilov/miniconda3/envs/embenv/lib/python3.8/site-packages/pyspark/python/lib/py4j-0.10.9-src.zip/py4j/java_gateway.py", line 977, in _get_connection
    connection = self.deque.pop()
IndexError: pop from an empty deque

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/data/ikruzhilov/miniconda3/envs/embenv/lib/python3.8/site-packages/pyspark/python/lib/py4j-0.10.9-src.zip/py4j/java_gateway.py", line 1115, in start
    self.socket.connect((self.address, self.port))
ConnectionRefusedError: [Errno 111] Connection refused
start                  : An error occurred while trying to connect to the Java server (127.0.0.1:45145)
Traceback (most recent call last):
  File "/mnt/data/ikruzhilov/miniconda3/envs/embenv/lib/python3.8/site-packages/pyspark/python/lib/py4j-0.10.9-src.zip/py4j/java_gateway.py", line 977, in _get_connection
    connection = self.deque.pop()
IndexError: pop from an empty deque

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/data/ikruzhilov/miniconda3/envs/embenv/lib/python3.8/site-packages/pyspark/python/lib/py4j-0.10.9-src.zip/py4j/java_gateway.py", line 1115, in start
    self.socket.connect((self.address, self.port))
ConnectionRefusedError: [Errno 111] Connection refused
start                  : An error occurred while trying to connect to the Java server (127.0.0.1:45145)
Traceback (most recent call last):
  File "/mnt/data/ikruzhilov/miniconda3/envs/embenv/lib/python3.8/site-packages/pyspark/python/lib/py4j-0.10.9-src.zip/py4j/java_gateway.py", line 977, in _get_connection
    connection = self.deque.pop()
IndexError: pop from an empty deque

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/data/ikruzhilov/miniconda3/envs/embenv/lib/python3.8/site-packages/pyspark/python/lib/py4j-0.10.9-src.zip/py4j/java_gateway.py", line 1115, in start
    self.socket.connect((self.address, self.port))
ConnectionRefusedError: [Errno 111] Connection refused
start                  : An error occurred while trying to connect to the Java server (127.0.0.1:45145)
Traceback (most recent call last):
  File "/mnt/data/ikruzhilov/miniconda3/envs/embenv/lib/python3.8/site-packages/pyspark/python/lib/py4j-0.10.9-src.zip/py4j/java_gateway.py", line 977, in _get_connection
    connection = self.deque.pop()
IndexError: pop from an empty deque

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/data/ikruzhilov/miniconda3/envs/embenv/lib/python3.8/site-packages/pyspark/python/lib/py4j-0.10.9-src.zip/py4j/java_gateway.py", line 1115, in start
    self.socket.connect((self.address, self.port))
ConnectionRefusedError: [Errno 111] Connection refused
start                  : An error occurred while trying to connect to the Java server (127.0.0.1:45145)
Traceback (most recent call last):
  File "/mnt/data/ikruzhilov/miniconda3/envs/embenv/lib/python3.8/site-packages/pyspark/python/lib/py4j-0.10.9-src.zip/py4j/java_gateway.py", line 977, in _get_connection
    connection = self.deque.pop()
IndexError: pop from an empty deque

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/data/ikruzhilov/miniconda3/envs/embenv/lib/python3.8/site-packages/pyspark/python/lib/py4j-0.10.9-src.zip/py4j/java_gateway.py", line 1115, in start
    self.socket.connect((self.address, self.port))
ConnectionRefusedError: [Errno 111] Connection refused
start                  : An error occurred while trying to connect to the Java server (127.0.0.1:45145)
Traceback (most recent call last):
  File "/mnt/data/ikruzhilov/miniconda3/envs/embenv/lib/python3.8/site-packages/pyspark/python/lib/py4j-0.10.9-src.zip/py4j/java_gateway.py", line 977, in _get_connection
    connection = self.deque.pop()
IndexError: pop from an empty deque

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/data/ikruzhilov/miniconda3/envs/embenv/lib/python3.8/site-packages/pyspark/python/lib/py4j-0.10.9-src.zip/py4j/java_gateway.py", line 1115, in start
    self.socket.connect((self.address, self.port))
ConnectionRefusedError: [Errno 111] Connection refused
start                  : An error occurred while trying to connect to the Java server (127.0.0.1:45145)
Traceback (most recent call last):
  File "/mnt/data/ikruzhilov/miniconda3/envs/embenv/lib/python3.8/site-packages/pyspark/python/lib/py4j-0.10.9-src.zip/py4j/java_gateway.py", line 977, in _get_connection
    connection = self.deque.pop()
IndexError: pop from an empty deque

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/data/ikruzhilov/miniconda3/envs/embenv/lib/python3.8/site-packages/pyspark/python/lib/py4j-0.10.9-src.zip/py4j/java_gateway.py", line 1115, in start
    self.socket.connect((self.address, self.port))
ConnectionRefusedError: [Errno 111] Connection refused
start                  : An error occurred while trying to connect to the Java server (127.0.0.1:45145)
Traceback (most recent call last):
  File "/mnt/data/ikruzhilov/miniconda3/envs/embenv/lib/python3.8/site-packages/pyspark/python/lib/py4j-0.10.9-src.zip/py4j/java_gateway.py", line 977, in _get_connection
    connection = self.deque.pop()
IndexError: pop from an empty deque

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/data/ikruzhilov/miniconda3/envs/embenv/lib/python3.8/site-packages/pyspark/python/lib/py4j-0.10.9-src.zip/py4j/java_gateway.py", line 1115, in start
    self.socket.connect((self.address, self.port))
ConnectionRefusedError: [Errno 111] Connection refused
start                  : An error occurred while trying to connect to the Java server (127.0.0.1:45145)
Traceback (most recent call last):
  File "/mnt/data/ikruzhilov/miniconda3/envs/embenv/lib/python3.8/site-packages/pyspark/python/lib/py4j-0.10.9-src.zip/py4j/java_gateway.py", line 977, in _get_connection
    connection = self.deque.pop()
IndexError: pop from an empty deque

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/data/ikruzhilov/miniconda3/envs/embenv/lib/python3.8/site-packages/pyspark/python/lib/py4j-0.10.9-src.zip/py4j/java_gateway.py", line 1115, in start
    self.socket.connect((self.address, self.port))
ConnectionRefusedError: [Errno 111] Connection refused
start                  : An error occurred while trying to connect to the Java server (127.0.0.1:45145)
Traceback (most recent call last):
  File "/mnt/data/ikruzhilov/miniconda3/envs/embenv/lib/python3.8/site-packages/pyspark/python/lib/py4j-0.10.9-src.zip/py4j/java_gateway.py", line 977, in _get_connection
    connection = self.deque.pop()
IndexError: pop from an empty deque

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/data/ikruzhilov/miniconda3/envs/embenv/lib/python3.8/site-packages/pyspark/python/lib/py4j-0.10.9-src.zip/py4j/java_gateway.py", line 1115, in start
    self.socket.connect((self.address, self.port))
ConnectionRefusedError: [Errno 111] Connection refused
start                  : An error occurred while trying to connect to the Java server (127.0.0.1:45145)
Traceback (most recent call last):
  File "/mnt/data/ikruzhilov/miniconda3/envs/embenv/lib/python3.8/site-packages/pyspark/python/lib/py4j-0.10.9-src.zip/py4j/java_gateway.py", line 977, in _get_connection
    connection = self.deque.pop()
IndexError: pop from an empty deque

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/data/ikruzhilov/miniconda3/envs/embenv/lib/python3.8/site-packages/pyspark/python/lib/py4j-0.10.9-src.zip/py4j/java_gateway.py", line 1115, in start
    self.socket.connect((self.address, self.port))
ConnectionRefusedError: [Errno 111] Connection refused
start                  : An error occurred while trying to connect to the Java server (127.0.0.1:45145)
Traceback (most recent call last):
  File "/mnt/data/ikruzhilov/miniconda3/envs/embenv/lib/python3.8/site-packages/pyspark/python/lib/py4j-0.10.9-src.zip/py4j/java_gateway.py", line 977, in _get_connection
    connection = self.deque.pop()
IndexError: pop from an empty deque

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/data/ikruzhilov/miniconda3/envs/embenv/lib/python3.8/site-packages/pyspark/python/lib/py4j-0.10.9-src.zip/py4j/java_gateway.py", line 1115, in start
    self.socket.connect((self.address, self.port))
ConnectionRefusedError: [Errno 111] Connection refused
start                  : An error occurred while trying to connect to the Java server (127.0.0.1:45145)
Traceback (most recent call last):
  File "/mnt/data/ikruzhilov/miniconda3/envs/embenv/lib/python3.8/site-packages/pyspark/python/lib/py4j-0.10.9-src.zip/py4j/java_gateway.py", line 977, in _get_connection
    connection = self.deque.pop()
IndexError: pop from an empty deque

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/data/ikruzhilov/miniconda3/envs/embenv/lib/python3.8/site-packages/pyspark/python/lib/py4j-0.10.9-src.zip/py4j/java_gateway.py", line 1115, in start
    self.socket.connect((self.address, self.port))
ConnectionRefusedError: [Errno 111] Connection refused
start                  : An error occurred while trying to connect to the Java server (127.0.0.1:45145)
Traceback (most recent call last):
  File "/mnt/data/ikruzhilov/miniconda3/envs/embenv/lib/python3.8/site-packages/pyspark/python/lib/py4j-0.10.9-src.zip/py4j/java_gateway.py", line 977, in _get_connection
    connection = self.deque.pop()
IndexError: pop from an empty deque

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/data/ikruzhilov/miniconda3/envs/embenv/lib/python3.8/site-packages/pyspark/python/lib/py4j-0.10.9-src.zip/py4j/java_gateway.py", line 1115, in start
    self.socket.connect((self.address, self.port))
ConnectionRefusedError: [Errno 111] Connection refused
start                  : An error occurred while trying to connect to the Java server (127.0.0.1:45145)
Traceback (most recent call last):
  File "/mnt/data/ikruzhilov/miniconda3/envs/embenv/lib/python3.8/site-packages/pyspark/python/lib/py4j-0.10.9-src.zip/py4j/java_gateway.py", line 977, in _get_connection
    connection = self.deque.pop()
IndexError: pop from an empty deque

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/data/ikruzhilov/miniconda3/envs/embenv/lib/python3.8/site-packages/pyspark/python/lib/py4j-0.10.9-src.zip/py4j/java_gateway.py", line 1115, in start
    self.socket.connect((self.address, self.port))
ConnectionRefusedError: [Errno 111] Connection refused
start                  : An error occurred while trying to connect to the Java server (127.0.0.1:45145)
Traceback (most recent call last):
  File "/mnt/data/ikruzhilov/miniconda3/envs/embenv/lib/python3.8/site-packages/pyspark/python/lib/py4j-0.10.9-src.zip/py4j/java_gateway.py", line 977, in _get_connection
    connection = self.deque.pop()
IndexError: pop from an empty deque

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/data/ikruzhilov/miniconda3/envs/embenv/lib/python3.8/site-packages/pyspark/python/lib/py4j-0.10.9-src.zip/py4j/java_gateway.py", line 1115, in start
    self.socket.connect((self.address, self.port))
ConnectionRefusedError: [Errno 111] Connection refused
start                  : An error occurred while trying to connect to the Java server (127.0.0.1:45145)
Traceback (most recent call last):
  File "/mnt/data/ikruzhilov/miniconda3/envs/embenv/lib/python3.8/site-packages/pyspark/python/lib/py4j-0.10.9-src.zip/py4j/java_gateway.py", line 977, in _get_connection
    connection = self.deque.pop()
IndexError: pop from an empty deque

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/data/ikruzhilov/miniconda3/envs/embenv/lib/python3.8/site-packages/pyspark/python/lib/py4j-0.10.9-src.zip/py4j/java_gateway.py", line 1115, in start
    self.socket.connect((self.address, self.port))
ConnectionRefusedError: [Errno 111] Connection refused
start                  : An error occurred while trying to connect to the Java server (127.0.0.1:45145)
Traceback (most recent call last):
  File "/mnt/data/ikruzhilov/miniconda3/envs/embenv/lib/python3.8/site-packages/pyspark/python/lib/py4j-0.10.9-src.zip/py4j/java_gateway.py", line 977, in _get_connection
    connection = self.deque.pop()
IndexError: pop from an empty deque

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/data/ikruzhilov/miniconda3/envs/embenv/lib/python3.8/site-packages/pyspark/python/lib/py4j-0.10.9-src.zip/py4j/java_gateway.py", line 1115, in start
    self.socket.connect((self.address, self.port))
ConnectionRefusedError: [Errno 111] Connection refused
